In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('swarm_train_data.csv')

C:\Users\faith\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


## descriptive statistics, EDA, data preprocessing

In [3]:
df.head()

x1      y1  xVel1  yVel1  xA1  yA1   xS1   yS1   xC1   yC1  ...  \
0 -489.28 -658.11   2.51   3.28  0.0  0.0 -0.26  0.35  0.93 -0.37  ...   
1 -540.61 -670.93  -1.02  -4.76  0.0  0.0 -0.06  0.44  0.24 -0.97  ...   
2  379.83 -521.18   1.86   7.31  0.0  0.0  0.00  0.00  0.00  0.00  ...   
3  888.21 -146.53  -2.67 -18.10  0.0  0.0  0.00  0.00  0.00  0.00  ...   
4 -452.43 -632.15   2.66  -2.63  0.0  0.0 -0.12  0.42  0.01 -1.00  ...   

   yVel200  xA200  yA200  xS200  yS200  xC200  yC200  nAC200  nS200  Class   
0    -4.17    0.0    0.0   0.33   0.29  -0.87  -0.50     112     40       1  
1    -4.43    0.0    0.0  -0.15   0.41  -0.46  -0.89     112      9       1  
2     1.33    0.0    0.0   0.00   0.00   0.00   0.00       4      0       1  
3    -2.19    0.0    0.0   0.00   0.00   0.00   0.00       3      1       0  
4     2.54    0.0    0.0   0.00   0.00  -1.00  -0.10     112      0       1  

[5 rows x 2401 columns]

In [4]:
df.shape

(18013, 2401)

In [5]:
df.info

<bound method DataFrame.info of             x1      y1  xVel1  yVel1   xA1   yA1   xS1   yS1   xC1   yC1  ...  \
0      -489.28 -658.11   2.51   3.28  0.00  0.00 -0.26  0.35  0.93 -0.37  ...   
1      -540.61 -670.93  -1.02  -4.76  0.00  0.00 -0.06  0.44  0.24 -0.97  ...   
2       379.83 -521.18   1.86   7.31  0.00  0.00  0.00  0.00  0.00  0.00  ...   
3       888.21 -146.53  -2.67 -18.10  0.00  0.00  0.00  0.00  0.00  0.00  ...   
4      -452.43 -632.15   2.66  -2.63  0.00  0.00 -0.12  0.42  0.01 -1.00  ...   
...        ...     ...    ...    ...   ...   ...   ...   ...   ...   ...  ...   
18008  -574.72 -176.30  -5.15  -5.88  0.00  0.00  0.00  0.00  0.00  0.00  ...   
18009  -192.91 -997.61   5.70  -0.92 -0.14 -0.29  0.00  0.00  0.19  0.25  ...   
18010   273.54  841.54  -4.74  -5.54 -0.73 -0.69  0.00  0.00  0.51 -0.86  ...   
18011  1096.38 -270.36  -6.87  -0.65 -0.56  0.03  0.00  0.00 -0.32  0.05  ...   
18012   237.53 -712.97   1.98   7.16  0.00  1.00  0.00  0.00  0.00  0.00  ...

In [6]:
df.describe() #mean,std,count

y1         xVel1         yVel1           xA1           yA1  \
count  18013.000000  18013.000000  18013.000000  18013.000000  18013.000000   
mean     -76.184822     -0.733670      0.183239     -0.148906      0.158274   
std      572.116169      6.409622      7.376411      0.376818      0.593320   
min    -1010.420000    -18.590000    -18.410000     -1.000000     -1.000000   
25%     -612.120000     -5.410000     -5.640000     -0.240000      0.000000   
50%     -160.550000     -0.440000     -1.360000      0.000000      0.000000   
75%      418.170000      3.750000      7.390000      0.000000      0.970000   
max     1012.960000     18.470000     18.630000      1.000000      1.040000   

                xS1           yS1           xC1           yC1          nAC1  \
count  18013.000000  18013.000000  18013.000000  18013.000000  18013.000000   
mean      -1.304686     -0.870929     -0.037237      0.076594     19.172986   
std       29.355828     22.649405      0.565769      0.637191     23.389772   
min     -944.070000   -847.910000     -2.680000     -2.680000      0.000000   
25%        0.000000      0.000000     -0.040000     -0.020000      3.000000   
50%        0.000000      0.000000      0.000000      0.000000      8.000000   
75%        0.000000      0.000000      0.000000      0.020000     32.000000   
max       68.560000    234.740000      2.680000      2.680000    157.000000   

       ...       yVel200         xA200         yA200         xS200  \
count  ...  18013.000000  18013.000000  18013.000000  18013.000000   
mean   ...      0.215071     -0.125053      0.134539     -1.656987   
std    ...      7.679787      0.380890      0.572069     77.155840   
min    ...    -18.440000     -1.040000     -1.000000  -4079.230000   
25%    ...     -5.440000     -0.200000      0.000000      0.000000   
50%    ...     -0.540000      0.000000      0.000000      0.000000   
75%    ...      7.580000      0.000000      0.650000      0.000000   
max    ...     18.530000      1.000000      1.040000    255.990000   

              yS200         xC200         yC200        nAC200         nS200  \
count  18013.000000  18013.000000  18013.000000  18013.000000  18013.000000   
mean      -0.080935     -0.015850      0.090184     26.488925      2.190029   
std        7.402642      0.559505      0.622581     34.253546      7.633302   
min     -370.240000     -2.680000     -2.680000      0.000000      0.000000   
25%        0.000000     -0.080000      0.000000      2.000000      0.000000   
50%        0.000000      0.000000      0.000000     12.000000      0.000000   
75%        0.000000      0.000000      0.040000     35.000000      1.000000   
max       68.940000      2.680000      2.680000    142.000000     64.000000   

             Class   
count  18013.000000  
mean       0.516682  
std        0.499735  
min        0.000000  
25%        0.000000  
50%        1.000000  
75%        1.000000  
max        1.000000  

[8 rows x 2400 columns]

In [7]:
df.isna().sum()

x1        0
y1        0
xVel1     0
yVel1     0
xA1       0
         ..
xC200     0
yC200     0
nAC200    0
nS200     0
Class     0
Length: 2401, dtype: int64

In [8]:
df['x1'] = pd.to_numeric(df['x1'], errors= 'coerce')

In [9]:
X = df['x1']

In [10]:
X

0        -489.28
1        -540.61
2         379.83
3         888.21
4        -452.43
          ...   
18008    -574.72
18009    -192.91
18010     273.54
18011    1096.38
18012     237.53
Name: x1, Length: 18013, dtype: float64

In [11]:
X.isna().sum()

1

In [12]:
X = X.fillna(method = 'ffill')

In [13]:
X.isna().sum()

0

In [14]:
type(X)

pandas.core.series.Series

In [15]:
X.values

array([-489.28, -540.61,  379.83, ...,  273.54, 1096.38,  237.53])

In [16]:
X = X.values

In [17]:
X = X.reshape(-1,1)
X.shape

(18013, 1)

In [18]:
y = df['Class ']

In [19]:
y

0        1
1        1
2        1
3        0
4        1
        ..
18008    0
18009    0
18010    1
18011    1
18012    0
Name: Class , Length: 18013, dtype: int64

## building simple model

In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn

KNeighborsClassifier()

In [21]:
knn.fit(X,y)

KNeighborsClassifier()

In [22]:
knn.score(X,y)

0.7092100149891745

In [23]:
knn.predict([[107]])

array([1], dtype=int64)

In [24]:
knn.predict([[916]])

array([0], dtype=int64)

## building other hyperparameterized models

In [25]:
from sklearn.model_selection import train_test_split
knn1 = KNeighborsClassifier()

In [26]:
train_test_split(X,y)

[array([[-1018.92],
        [  735.15],
        [ -668.87],
        ...,
        [  935.62],
        [  419.71],
        [-1062.15]]),
 array([[  657.97],
        [ 1193.82],
        [ 1057.01],
        ...,
        [ -140.1 ],
        [-1358.45],
        [ -287.74]]),
 2470     0
 9428     1
 17545    0
 201      1
 17009    1
         ..
 902      1
 17849    0
 10391    1
 16782    0
 13221    1
 Name: Class , Length: 13509, dtype: int64,
 11621    0
 17476    0
 6418     0
 4282     0
 3403     0
         ..
 17719    1
 12511    0
 6871     1
 3512     0
 2558     0
 Name: Class , Length: 4504, dtype: int64]

In [27]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)

In [28]:
knn1.fit(X_train, y_train)

KNeighborsClassifier()

In [29]:
knn1.score(X_train, y_train)

0.7133793322230153

In [30]:
knn1.score(X_test, y_test)

0.551258327165063

In [31]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model

LinearRegression()

In [32]:
model.fit(X,y)

LinearRegression()

In [33]:
model.score(X,y)

0.001211466335512279

## test dataset

In [34]:
df1 = pd.read_csv('swarm_test_data.csv')

In [35]:
df1.isna().sum()

x1        0
y1        0
xVel1     0
yVel1     0
xA1       0
         ..
yS200     0
xC200     0
yC200     0
nAC200    0
nS200     0
Length: 2400, dtype: int64

In [36]:
df1['x1'] = pd.to_numeric(df1['x1'], errors= 'coerce')

In [37]:
X = df1['x1']

In [38]:
X

0       -310.36
1        875.60
2        257.97
3        995.13
4       -782.80
         ...   
5998   -1400.85
5999    -535.60
6000     973.72
6001    1073.24
6002     494.28
Name: x1, Length: 6003, dtype: float64

In [39]:
X.isna().sum()

0

In [40]:
X = X.values

In [41]:
X = X.reshape(-1,1)
X.shape

(6003, 1)

In [42]:
y = df['Class ']

In [43]:
y

0        1
1        1
2        1
3        0
4        1
        ..
18008    0
18009    0
18010    1
18011    1
18012    0
Name: Class , Length: 18013, dtype: int64

In [92]:
# from sklearn.neighbors import KNeighborsClassifier
# knn_new = KNeighborsClassifier(metric='manhattan')
# knn_new.fit(X,y)
# knn_new.score(X,y)

ValueError: Found input variables with inconsistent numbers of samples: [6003, 18013]

In [ ]:
np.array