In [1]:
import numpy as np

In [2]:
a=np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
s=slice(2,7,2) #start at 2, stop at 7with stepsize of 2

In [7]:
print (a[s])

[2 4 6]


In [9]:
c=np.arange(10)
d=c[2:7:2]
print (d)

[2 4 6]


In [10]:
print(c[2:])

[2 3 4 5 6 7 8 9]


In [13]:
z = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (z[1:])

[[4 5 6]
 [7 8 9]]


In [14]:
x = np.array([[1,2], [3,4], [5,6]])
y = x[[0,1,2], [0,1,0]] ## y takes from position(0,0), (1,1), (2,0)
print (y) 

[1 4 5]


In [16]:
x = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])
row = np.array([[0,0], [3,3]])
col = np.array([[0,2], [0,2]])
y = x[row,col]

print(y)

[[ 0  2]
 [ 9 11]]
