In [10]:
import numpy as np

In [11]:
import math

In [12]:
a=[2,5,3,4]

In [13]:
math.sin(4)

-0.7568024953079282

In [14]:
a1=np.array(a)

In [15]:
a1

array([2, 5, 3, 4])

In [9]:
np.sin(a1)

array([ 0.90929743, -0.95892427,  0.14112001, -0.7568025 ])

In [16]:
np.abs(a)

array([2, 5, 3, 4])

In [17]:
np.mean(a1)

3.5

In [18]:
np.min(a1)

2

In [19]:
np.argmax(a1) #position of max, at index 1

1

In [21]:
np.argmin(a1) #position of min, at index 0

0

In [22]:
#aggregate function

In [23]:
np.std(a1)

1.118033988749895

In [24]:
np.var(a1)

1.25

In [26]:
scores=np.random.randint(0,101,10)

In [27]:
scores

array([55, 42, 38, 56, 67, 53, 47, 22, 80, 84])

In [29]:
scores=np.random.randint(0,101,(3,4))

In [30]:
scores

array([[ 6, 52,  8, 11],
       [22, 66, 19, 48],
       [71, 32, 24, 54]])

In [31]:
np.mean(scores)

34.416666666666664

In [33]:
scores.mean()

34.416666666666664

In [35]:
np.median(scores)

28.0

In [39]:
scores.max()

71

In [40]:
scores.argmax()

8

## Axis

In [41]:
np.sum(scores)

413

In [42]:
np.sum(scores, axis=0)#sum down the column

array([ 99, 150,  51, 113])

In [43]:
np.sum(scores, axis=1)#sum across the row

array([ 77, 155, 181])

In [44]:
scores

array([[ 6, 52,  8, 11],
       [22, 66, 19, 48],
       [71, 32, 24, 54]])

In [45]:
np.mean(scores,axis=0)

array([33.        , 50.        , 17.        , 37.66666667])

In [46]:
np.argmax(np.mean(scores,axis=0)) #position of highest average performance

1

In [47]:
np.argmin(np.mean(scores,axis=0)) #position of lowest average performance

2

## broadcasting

In [49]:
a1

array([2, 5, 3, 4])

In [50]:
a1+2

array([4, 7, 5, 6])

In [51]:
a1**3

array([  8, 125,  27,  64], dtype=int32)

In [52]:
x=np.linspace(10,100,7) #start,stop, how many items to be generated

In [53]:
x

array([ 10.,  25.,  40.,  55.,  70.,  85., 100.])

In [56]:
y=np.arange(10,101,7) #start, stop, stepsize

In [57]:
y

array([10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94])

In [58]:
y=np.arange(10,101,15)

In [59]:
y

array([ 10,  25,  40,  55,  70,  85, 100])

In [60]:
y=np.linspace(20,70,3)

In [61]:
y

array([20., 45., 70.])

In [62]:
z=np.random.randint(12,200,9)

In [63]:
z

array([ 35, 166, 180,  97,  69,  85, 163,  39,  98])

In [64]:
y

array([20., 45., 70.])

In [65]:
y+z

ValueError: operands could not be broadcast together with shapes (3,) (9,) 

In [66]:
z1=np.array([4])

In [67]:
z1+z

array([ 39, 170, 184, 101,  73,  89, 167,  43, 102])

In [68]:
z

array([ 35, 166, 180,  97,  69,  85, 163,  39,  98])

In [69]:
z.shape

(9,)

In [70]:
z.shape=(3,3)

In [71]:
z

array([[ 35, 166, 180],
       [ 97,  69,  85],
       [163,  39,  98]])

In [72]:
z+z1

array([[ 39, 170, 184],
       [101,  73,  89],
       [167,  43, 102]])

In [73]:
y

array([20., 45., 70.])

In [74]:
z+y

array([[ 55., 211., 250.],
       [117., 114., 155.],
       [183.,  84., 168.]])

In [75]:
y1=y[:2]

In [76]:
y1

array([20., 45.])

In [77]:
y1+z

ValueError: operands could not be broadcast together with shapes (2,) (3,3) 

In [78]:
a1=np.random.randint(1,10,(2,3))

In [79]:
a1

array([[3, 2, 7],
       [6, 4, 6]])

In [80]:
b1=np.random.randint(1,10,(1,3))

In [81]:
b1

array([[7, 4, 1]])

In [82]:
b2=np.random.randint(1,10,(2,1))

In [83]:
b2

array([[2],
       [2]])

In [84]:
a1+b2

array([[5, 4, 9],
       [8, 6, 8]])

In [85]:
a1+b1

array([[10,  6,  8],
       [13,  8,  7]])

In [89]:
b3=np.random.randint(1,2,(2,2))

In [90]:
b3

array([[1, 1],
       [1, 1]])

In [91]:
a1

array([[3, 2, 7],
       [6, 4, 6]])

In [92]:
b3+a1

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [98]:
a2=np.random.randint(2,12,(2,4))#2rows, 4 col

In [101]:
a2=np.random.randint(2,12,(4,2))#4rows, 2 col

In [102]:
a2

array([[11,  2],
       [10,  9],
       [ 5,  6],
       [10,  6]])

In [95]:
b3

array([[1, 1],
       [1, 1]])

In [104]:
a2+b3[1]

array([[12,  3],
       [11, 10],
       [ 6,  7],
       [11,  7]])